Repository IkramKhan-DevOps/frent-neonapps, pull requests merged in 2025-01, with the labels that each got.

#6 Feat: max length updated on login
  src/api/auth/serializers.py
Labels: documentation, enhancement

#7 Signup issue and Other Apis Added
  src/api/auth/serializers.py
  src/api/auth/urls.py
  src/api/auth/views.py
  src/api/v1/serializers.py
  src/api/v1/urls.py
  src/api/v1/views.py
  src/services/users/admin.py
  src/services/users/api/serializers.py
  src/services/users/api/urls.py
  src/services/users/api/views.py
  src/services/users/models.py
  src/web/accounts/adapters.py
Labels: documentation, enhancement

#8 NEW Order APP + DB Models added + 13 New APIS Added
  requirements.txt
  root/settings.py
  root/urls.py
  src/services/order/__init__.py
  src/services/order/admin.py
  src/services/order/api/filters.py
  src/services/order/api/serializers.py
  src/services/order/api/urls.py
  src/services/order/api/views.py
  src/services/order/apps.py
  src/services/order/models.py
  src/services/order/tests.py
  src/services/order/urls.py
  src/services/order/views.py
  src/services/services/api/serializers.py
  src/services/services/api/views.py
  src/services/users/admin.py
  src/services/users/api/serializers.py
  src/services/users/api/urls.py
  src/services/users/api/views.py
  src/services/users/models.py
Labels: documentation, enhancement

#9 Api : Interets and Lnaguage api updated
  src/services/order/api/urls.py
  src/services/users/api/urls.py
  src/services/users/api/views.py
Labels: documentation, enhancement

#10 Api : Interets api updated
  src/services/users/api/views.py
Labels: bug, enhancement

#11 Currency Serializer added to service list
  src/services/services/api/serializers.py
Labels: documentation, enhancement

#12 API : ID added to Users
  root/settings.py
  src/services/order/api/serializers.py
  src/services/order/models.py
  src/services/users/api/views.py
Labels: documentation, enhancement

#14 ListCreate APi View Added TO foavorites
  src/services/users/api/views.py
Labels: documentation, enhancement

#16 Api : Currency Api Inplemented
  src/services/services/api/urls.py
  src/services/services/api/views.py
Labels: documentation, enhancement

#17 Admin Dashboard
  README.md
  root/urls.py
  src/apps/stripe/templates/stripe/stripecustomer_list.html
  src/apps/whisper/templates/whisper/emailnotification_list.html
  src/core/templatetags/core_tags.py
  src/services/services/templates/services/service_detail.html
  src/services/services/templates/services/service_list.html
  src/services/users/models.py
  src/services/users/templates/users/admin_password_reset.html
  src/services/users/templates/users/user_detail.html
  src/services/users/templates/users/user_list.html
  src/services/users/views.py
  src/services/wallet/models.py
  src/services/wallet/templates/wallet/transaction_list.html
  src/services/wallet/templates/wallet/user_transaction.html
  src/services/wallet/templates/wallet/user_wallet.html
  src/services/wallet/urls.py
  src/services/wallet/views.py
  static/core/images/socialmedia/facebook_5968764.png
  static/core/images/socialmedia/instagram_2111463.png
  static/core/images/socialmedia/linkedin_3536569.png
  static/core/images/socialmedia/twitter_5968830.png
  templates/account/auth_base.html
  templates/account/base.html
  templates/include/admin/admin_header.html
  templates/include/admin/admin_nav.html
Labels: bug, enhancement

#18 Wallet , Order , Service Booking and Advertisement
  root/settings.py
  src/core/models.py
  src/services/order/admin.py
  src/services/order/api/serializers.py
  src/services/order/api/urls.py
  src/services/order/api/views.py
  src/services/order/apps.py
  src/services/order/models.py
  src/services/order/signals.py
  src/services/services/admin.py
  src/services/services/api/serializers.py
  src/services/services/api/urls.py
  src/services/services/api/views.py
  src/services/services/apps.py
  src/services/services/models.py
  src/services/services/signals.py
  src/services/wallet/admin.py
  src/services/wallet/api/filters.py
  src/services/wallet/api/serializers.py
  src/services/wallet/api/urls.py
  src/services/wallet/api/views.py
  src/services/wallet/apps.py
  src/services/wallet/models.py
  src/services/wallet/signals.py
  src/services/wallet/urls.py
Labels: bug, documentation, enhancement

#20 Setting : allauth middelware added to settings
  root/settings.py
  src/services/services/api/serializers.py
  src/services/services/api/views.py
Labels: documentation, enhancement

#21 Deleted Serlizers imports are removed from views
  src/services/services/api/views.py
Labels: documentation, enhancement

#22 Services : Rule and Instruction api are added
  src/services/services/api/serializers.py
  src/services/services/api/urls.py
  src/services/services/api/views.py
  src/services/services/models.py
Labels: documentation, enhancement

#23 UserFavorite Api queryset updated
  src/services/users/api/views.py
Labels: enhancement

#24 wallet APis are implement
  root/settings.py
  root/urls.py
  src/apps/stripe/api/serializers.py
  src/apps/stripe/api/urls.py
  src/apps/stripe/api/views.py
  src/apps/stripe/bll.py
  src/apps/stripe/urls.py
  src/apps/stripe/views.py
  src/apps/stripe/webhook_core.py
  src/services/services/api/filters.py
  src/services/services/models.py
  src/services/users/api/views.py
  src/services/users/models.py
Labels: documentation, enhancement

#25 2 New apis are added one for provider detail and anotheer for user tail
  src/services/services/api/serializers.py
  src/services/services/api/views.py
  src/services/users/api/urls.py
  src/services/users/api/views.py
  static/website/css/style.css
Labels: documentation, enhancement
